/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Componentes.Providers;

import helpers.UnderlineTexts;
import java.awt.Color;
import java.awt.font.TextAttribute;

/**
 *
 * @author Miguel
 */
public class ModuleProvider extends javax.swing.JPanel {

    private final Color primaryColor;
    private final Color secondaryColor;
    private final UnderlineTexts underlineObj;
    private final int underlineDashed;
    private final float weightBold;
    private final float weightRegular;
    private final int noUnderline;

    public ModuleProvider() {
        primaryColor = new Color(34, 138, 147);
        secondaryColor = new Color(53, 71, 73);
        underlineObj = new UnderlineTexts();
        underlineDashed = TextAttribute.UNDERLINE_LOW_DASHED;
        weightBold = TextAttribute.WEIGHT_BOLD;
        weightRegular = TextAttribute.WEIGHT_REGULAR;
        noUnderline = -1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 138, 147), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Component Provider");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel1)
                .addContainerGap(494, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabel1)
                .addContainerGap(403, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
